### ISSUE TITLE
About train encoder ?

### ISSUE THREAD

**Issue by GreenLimeSia** [bryandlee/stylegan2-encoder-pytorch#1]
Is it possible to provide the convert_weight code? It does not appear in Seonghyeon Kim's Pytorch Implementation of StyleGAN2.
For example,  g_args = g_ckpt['args'], g_ckpt["d_optim"].

**Comment by bryandlee** [comment]
Hi, Seonghyeon Kim's pytorch implementation actually has the convert_weight code [here](https://github.com/rosinality/stylegan2-pytorch#convert-weight-from-official-checkpoints). 
For the encoder, I haven't tried converting the weights yet.
I'm still testing the code and planning to release the trained encoder weights later.

**Comment by GreenLimeSia** [comment]
Thanks for your reply!  But I have a question, the convert_weight code in Seonghyeon Kim's PyTorch implementation has no save "args" and "d_optim", would you mind tell me how to save the "args" and "d_optim" parameters from Tensorflow to Pytorch?

**Comment by bryandlee** [comment]
I guess you can simply pass the "args" as ckpt["args"] = tf_args. The parameters beta1, beta2, lr and previous states need to be loaded from the tf model file to convert "d_optim".

**Comment by GreenLimeSia** [comment]
Thanks for your reply! I will try it, Thank you very much.
