### ISSUE TITLE
Encoder + Model Interpolation

### ISSUE THREAD

**Issue by zhongtao93** [bryandlee/stylegan2-encoder-pytorch#11]
hi, 
I have a question about the encoder+model interpolation. I have downloaded naver webtoon generator model, and I replaced high level layer with FFHQ model(test from 3-11 till 10-11, trucation=0.6), but I can't get the same result as yours. Can you give   me some advices? Or there are some different hyperparametric?
Hoping for your reply!
![projections_10-11-0 6](https://user-images.githubusercontent.com/15263824/130413306-e4dde077-da2f-4cf6-bcf8-53429b0b9c2c.png)

**Comment by zhongtao93** [comment]
Anyone have idea about this？

**Comment by bryandlee** [comment]
Hi, I guess the webtoon checkpoint is different.

**Comment by zhongtao93** [comment]
I got it! If the latent code Z1 is from `generator.get_latent()`, the result is good, but if the latent code Z2 is from the Encoder dirctly, the result becomes bad. After some iterative optimization of the latent code Z2 may make result better.
