### ISSUE TITLE
generator_ffhq.pt

### ISSUE THREAD

**Issue by ronsoohyeong** [bryandlee/stylegan2-encoder-pytorch#5]
Thanks for your work.
By the way, interpolate.ipynb tries to load the checkpoint './checkpoint/generator_ffhq.pt', but it is missing.
Can you please let me know how to get it?

Best regards,
Ron

**Comment by bryandlee** [comment]
Hi, the generator weights can be found [here](https://github.com/rosinality/stylegan2-pytorch).

**Comment by ronsoohyeong** [comment]
Thanks for the prompt response, but there is only 550000.pt in the link, and if I change the name to 'generator_ffhq.pt', it doesn't work. Maybe the site that you referred to stopped providing the 'generator_ffhq.pt'. It would be very helpful if you kindly provide the checkpoint that you used.

**Comment by bryandlee** [comment]
Sorry for the confusion. I forgot to mention the additional parameters I used. [This](https://drive.google.com/file/d/1TH77dUsqcq50htIZT6DljFYr4T_ziJli/view?usp=sharing) should work!

**Comment by StelaBou** [comment]
Hello, 
is the 'generator_ffhq.pt'  the same with the one from [Here](https://github.com/rosinality/stylegan2-pytorch]) (550000.pt)?
Thanks.
